name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
          include-prerelease: true
      - name: Restore dependencies
        run: dotnet restore
      - name: dotnet-build
        run: dotnet build --no-restore
      - name: dotnet-test
        run: dotnet test --no-build --verbosity normal 